import "package:get/get.dart";


class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "en_US": {
      "feederInformation": "Feeder Information",
      "off": "OFF",
      "loadsheddingSchedule": "Loadshedding Schedule",
      "totalBreakDowns": "Total Breakdowns",
      "hours": "hours",
      "effectedTime": "Effected Time",
      "duration": "Duration",
      "today": "Today",
      "daily": "Daily",
      "weekly": "Weekly",
      "monthly": "Monthly",
      "changesInSchedule": "Changes in Schedule",
      "effectedFromNextMonth" : "Effected From Next Month",
      "wind": "Wind",
      "humidity": "Humidity",
      "chancesofRain": "Chances of rain",
      "days": "Days",
      "profile": "Profile",
      "editProfile": "Edit Profile",
      "change": "Change",
      "notifications": "Notifications",
      "language": "Language",
      "support": "Support",
      "rateUs": "Rate us",
      "aboutus": "About us",
      "dontgetCaughtIntheDark": "Dont get caught in the dark",
      "getStarted": "Get Started",
      "login": "Login",
      "email": "Email",
      "password": "Password",
      "forgotPassword": "Forgot Password",
      "loginWithGoogle": "Login With Google",
      "donthaveAnAccount": "Don\"t have an account? Register",
      "registerYourAccount": "Register your account",
      "name": "Name",
      "ifyousignup": "If you sign up you agree to the terms and conditions and Privacy Policy.",
      "Signup": "Sign Up",
      "signupWithGoogle": "Sign up with Google",
      "alreadyhaveanaccount": "Already have an account"
      
    },
   'es_ES': {
  "feederInformation": "Información del alimentador",
  "off": "APAGADO",
  "loadsheddingSchedule": "Calendario de deslastre de carga",
  "totalBreakDowns": "Desgloses totales",
  "hours": "horas",
  "effectedTime": "Tiempo efectuado",
  "duration": "Duración",
  "today": "Hoy",
  "daily": "A diario",
  "weekly": "Semanalmente",
  "monthly": "Mensual",
  "changesInSchedule": "Cambios en el horario",
  "effectedFromNextMonth": "Efectuado a partir del próximo mes",
  "wind": "Viento",
  "humidity": "Humedad",
  "chancesofRain": "Probabilidades de lluvia",
  "days": "Días",
  "profile": "Perfil",
  "editProfile": "Editar perfil",
  "change": "Cambiar",
  "notifications": "Notificaciones",
  "language": "Idioma",
  "support": "Apoyo",
  "rateUs": "Nos califica",
  "aboutus": "Sobre nosotros",
  "dontgetCaughtIntheDark": "No te dejes atrapar por la oscuridad",
  "getStarted": "Empezar",
  "login": "Acceso",
  "email": "Correo electrónico",
  "password": "Contraseña",
  "forgotPassword": "Has olvidado tu contraseña",
  "loginWithGoogle": "Iniciar sesión con Google",
  "donthaveAnAccount": "¿No tienes una cuenta? ",
  "registerYourAccount": "Registra tu cuenta",
  "name": "Nombre",
  "ifyousignup": "Si te registras aceptas los términos y condiciones y la Política de Privacidad.",
  "Signup": "Inscribirse",
  "signupWithGoogle": "Regístrese con Google",
  "alreadyhaveanaccount": "Ya tienes una cuenta",
  "welcome": "Bienvenido"
}
  };

}